remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: [Movie-list]
description: [Hey! I'm making this for all the movie lovers. It includes movies of all genres

Feel free to add your favorite movies too ;)]